- name: Run frontend container
  community.docker.docker_container:
    name: front
    image: "{{ dockerhub_username }}/tp-devops-front:latest"
    state: started
    pull: true
    restart_policy: unless-stopped
    networks:
      - name: app-network