name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Write SSH private key
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ansible_key
          chmod 600 ansible_key

      # Optionnel : seulement si tu utilises Ansible Vault
      - name: Write Ansible Vault password
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > $GITHUB_WORKSPACE/vault_pass

      - name: Debug vault
        run: |
          echo "vault_pass content:"
          cat $GITHUB_WORKSPACE/vault_pass
          echo "vault_pass exists:"
          ls -la $GITHUB_WORKSPACE/vault_pass
          echo "group_vars content:"
          cat $GITHUB_WORKSPACE/ansible/group_vars/all.yml
          cat $GITHUB_WORKSPACE/ansible/group_vars/all.vault.yml

      - name: Run Ansible playbook
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
        run: |
          ansible-playbook -i inventories/setup.yml playbook_roles.yml \
            -e "ansible_ssh_private_key_file=$GITHUB_WORKSPACE/ansible_key" \
            -e "ansible_user=${{ secrets.ANSIBLE_USER }}" \
            --vault-password-file $GITHUB_WORKSPACE/vault_pass